name: Build and publish application binaries

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.kadena_cabal_cache_aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.kadena_cabal_cache_aws_secret_access_key }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.2']
        cabal: ['3.2.0.0']
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'macOS-10.14']
        cabalcache: ['true']
    env:
      ARTIFACT_BUCKET: kadena-cabal-cache
      ARTIFACT_FOLDER: chainweb-mining-client

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create env variables for git objects
      run: |
        echo "IS_RELEASE='${{ contains(github.event_name, 'release') }}'" >> $GITHUB_ENV
        echo "GIT_REF_SHORT='${GITHUB_REF#refs/heads/}'" >> $GITHUB_ENV
        echo "GIT_HEAD_REF_SHORT='${GITHUB_HEAD_REF#refs/heads/}'" >> $GITHUB_ENV
        echo "GIT_SHA_SHORT='$(git rev-parse --short HEAD || true)'" >> $GITHUB_ENV
    - name: Install GHC and Cabal
      uses: actions/setup-haskell@v1
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle-${{ github.sha }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle-
          ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle

    # Build
    - name: Update package database
      run: cabal v2-update
    - name: Configure build
      run: |
        cabal v2-build all --dry-run
        cabal v2-freeze
    - name: Sync from cabal cache
      if: matrix.cabalcache == 'true'
      uses: larskuhtz/cabal-cache-action@ecc751af6d31b3ed5a3b4aefdefd0ed6ef4cb414
      with:
        bucket: "kadena-cabal-cache"
        region: "us-east-1"
        folder: "${{ matrix.os }}"
        aws_access_key_id: "${{ secrets.kadena_cabal_cache_aws_access_key_id }}"
        aws_secret_access_key: "${{ secrets.kadena_cabal_cache_aws_secret_access_key }}"
    - name: Install build dependencies
      run: cabal v2-build --only-dependencies
    - name: Build
      run: cabal v2-build chainweb-mining-client

    # Publish Artifacts
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts/applications
        export VER=$(grep '^version' chainweb-mining-client.cabal | sed -e 's/.*: *//')
        cp $(find dist-newstyle/ -name 'chainweb-mining-client' -type f) artifacts/applications
        cp README.md artifacts/applications
        cp CHANGELOG.md artifacts/applications
        cp LICENSE artifacts/applications
        cp chainweb-mining-client.cabal artifacts/applications
        cp cabal.project artifacts/applications
        cp cabal.project.freeze artifacts/applications
    - name: Strip Binary
      run: strip artifacts/applications/chainweb-mining-client
    - name: Safe artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chainweb-mining-client.${{ matrix.ghc }}.${{ matrix.os }}
        path: artifacts/applications

    # Publish to S3
    - name: Define S3 locations
      if: always()
      run: |
        echo "BINFILE='chainweb-mining-client.${{ matrix.ghc }}.${{ matrix.os }}.${{ env.GIT_SHA_SHORT }}.tar.gz'" >> $GITHUB_ENV
        echo "BRANCH_BINFILE='chainweb-mining-client.${{ matrix.ghc }}.${{ matrix.os }}.${{ env.GIT_REF_SHORT }}.tar.gz'" >> $GITHUB_ENV
        echo "TAG_BINFILE='chainweb-mining-client.${{ matrix.ghc }}.${{ matrix.os }}.${{ env.GIT_TAG }}.tar.gz'" >> $GITHUB_ENV

    # Publish artifacts to S3
    - name: Publish to S3
      run: |
        aws --version
        tar -C ./artifacts/applications/ -czf $BINFILE chainweb-mining-client
        echo "aws s3 cp $BINFILE s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/"
        aws --debug s3 cp "$BINFILE" "s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/"
        echo "aws s3api put-object-acl --bucket $ARTIFACT_BUCKET --key=$ARTIFACT_FOLDER/$BINFILE --acl public-read"
        aws s3api put-object-acl --bucket "$ARTIFACT_BUCKET" --key="$ARTIFACT_FOLDER/$BINFILE" --acl public-read
    - name: Publish to S3 for master builds
      if: env.GIT_REF_SHORT == 'master'
      run: |
        aws s3 cp s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$BINFILE s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$BRANCH_BINFILE
        aws s3api put-object-acl --bucket $ARTIFACT_BUCKET --key=$ARTIFACT_FOLDER/$BRANCH_BINFILE --acl public-read
    - name: Publish to S3 for release tag builds
      if: contains(github.event_name, 'release') || startsWith(env.GIT_TAG, '1.')
      run: |
        aws s3 cp s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$BINFILE s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$TAG_BINFILE
        aws s3api put-object-acl --bucket $ARTIFACT_BUCKET --key=$ARTIFACT_FOLDER/$TAG_BINFILE --acl public-read

